# Generated by Django 4.2.7 on 2023-12-14 12:08

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="RustDesDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rid",
                    models.CharField(blank=True, max_length=60, verbose_name=_("客户端ID")),
                ),
                ("cpu", models.CharField(max_length=20, verbose_name=_("CPU"))),
                ("hostname", models.CharField(max_length=20, verbose_name=_("主机名"))),
                ("memory", models.CharField(max_length=20, verbose_name=_("内存"))),
                ("os", models.CharField(max_length=20, verbose_name=_("操作系统"))),
                ("uuid", models.CharField(max_length=60, verbose_name=_("uuid"))),
                (
                    "username",
                    models.CharField(blank=True, max_length=60, verbose_name=_("系统用户名")),
                ),
                ("version", models.CharField(max_length=20, verbose_name=_("客户端版本"))),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name=_("设备注册时间")),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name=_("设备更新时间")),
                ),
            ],
            options={
                "verbose_name": _("设备"),
                "verbose_name_plural": _("设备列表"),
                "ordering": ("-rid",),
            },
        ),
        migrations.CreateModel(
            name="RustDeskPeer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=16, verbose_name=_("用户ID"))),
                ("rid", models.CharField(max_length=60, verbose_name=_("客户端ID"))),
                ("username", models.CharField(max_length=20, verbose_name=_("系统用户名"))),
                ("hostname", models.CharField(max_length=30, verbose_name=_("操作系统名"))),
                ("alias", models.CharField(max_length=30, verbose_name=_("别名"))),
                ("platform", models.CharField(max_length=30, verbose_name=_("平台"))),
                ("tags", models.CharField(max_length=30, verbose_name=_("标签"))),
                ("rhash", models.CharField(max_length=60, verbose_name=_("设备链接密码"))),
            ],
            options={
                "verbose_name": _("Peers"),
                "verbose_name_plural": _("Peers table"),
                "ordering": ("-username",),
            },
        ),
        migrations.CreateModel(
            name="RustDeskTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name=_("ID"),
                    ),
                ),
                ("uid", models.CharField(max_length=16, verbose_name=_("所属用户ID"))),
                ("tag_name", models.CharField(max_length=60, verbose_name=_("标签名称"))),
                (
                    "tag_color",
                    models.CharField(blank=True, max_length=60, verbose_name=_("标签颜色")),
                ),
            ],
            options={
                "verbose_name": _("Tags"),
                "verbose_name_plural": _("Tags table"),
                "ordering": ("-uid",),
            },
        ),
        migrations.CreateModel(
            name="RustDeskToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, verbose_name=_("用户名"))),
                ("rid", models.CharField(max_length=16, verbose_name=_("RustDesk ID"))),
                ("uid", models.CharField(max_length=16, verbose_name=_("用户ID"))),
                ("uuid", models.CharField(max_length=60, verbose_name=_("uuid"))),
                (
                    "access_token",
                    models.CharField(
                        blank=True, max_length=60, verbose_name=_("access_token")
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name=_("登录时间")),
                ),
            ],
            options={
                "verbose_name": _("Token"),
                "verbose_name_plural": _("Token table"),
                "ordering": ("-username",),
            },
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name=_("ID"),
                    ),
                ),
                ("uid", models.CharField(max_length=16, verbose_name=_("用户ID"))),
                ("shash", models.CharField(max_length=60, verbose_name=_("链接Key"))),
                ("peers", models.CharField(max_length=20, verbose_name=_("机器ID列表"))),
                ("is_used", models.BooleanField(default=False, verbose_name=_("是否使用"))),
                ("is_expired", models.BooleanField(default=False, verbose_name=_("是否过期"))),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name=_("生成时间")),
                ),
            ],
            options={
                "verbose_name": _("分享链接"),
                "verbose_name_plural": _("链接列表"),
                "ordering": ("-create_time",),
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name=_("ID"),
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name=_("password"))),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name=_("last login")
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text=_("Designates that this user has all permissions without explicitly assigning them."),
                        verbose_name=_("superuser status"),
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name=_("用户名")),
                ),
                ("rid", models.CharField(max_length=16, verbose_name=_("RustDesk ID"))),
                ("uuid", models.CharField(max_length=60, verbose_name=_("uuid"))),
                (
                    "autoLogin",
                    models.BooleanField(default=True, verbose_name=_("autoLogin")),
                ),
                ("rtype", models.CharField(max_length=20, verbose_name=_("rtype"))),
                ("deviceInfo", models.TextField(blank=True, verbose_name=_("登录信息:"))),
                ("is_active", models.BooleanField(default=True, verbose_name=_("是否激活"))),
                ("is_admin", models.BooleanField(default=False, verbose_name=_("是否管理员"))),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text=_("The groups this user belongs to. A user will get all permissions granted to each of their groups."),
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name=_("groups"),
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text=_("Specific permissions for this user."),
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name=_("user permissions"),
                    ),
                ),
            ],
            options={
                "verbose_name": _("用户"),
                "verbose_name_plural": _("用户列表"),
                "permissions": (
                    ("view_task", _("Can see available tasks")),
                    ("change_task_status", _("Can change the status of tasks")),
                    ("close_task", _("Can remove a task by setting its status as closed")),
                ),
            },
        ),
    ]
