# Generated by Django 4.2.7 on 2024-03-15 23:52

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_rustdesdevice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rustdesdevice",
            options={
                "ordering": ("-rid",),
                "verbose_name": _("设备"),
                "verbose_name_plural": _("设备列表"),
            },
        ),
        migrations.AlterModelOptions(
            name="rustdeskpeer",
            options={
                "ordering": ("-username",),
                "verbose_name": _("Peers"),
                "verbose_name_plural": _("Peers列表"),
            },
        ),
        migrations.AlterModelOptions(
            name="rustdesktag",
            options={
                "ordering": ("-uid",),
                "verbose_name": _("Tags"),
                "verbose_name_plural": _("Tags列表"),
            },
        ),
        migrations.AlterModelOptions(
            name="rustdesktoken",
            options={
                "ordering": ("-username",),
                "verbose_name": _("Token"),
                "verbose_name_plural": _("Token列表"),
            },
        ),
        migrations.AlterModelOptions(
            name="sharelink",
            options={
                "ordering": ("-create_time",),
                "verbose_name": _("分享链接"),
                "verbose_name_plural": _("链接列表"),
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": (
                    ("view_task", _("Can see available tasks")),
                    ("change_task_status", _("Can change the status of tasks")),
                    ("close_task", _("Can remove a task by setting its status as closed")),
                ),
                "verbose_name": _("用户"),
                "verbose_name_plural": _("用户列表"),
            },
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("设备注册时间")),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="hostname",
            field=models.CharField(max_length=100, verbose_name=_("主机名")),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="memory",
            field=models.CharField(max_length=100, verbose_name=_("内存")),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="os",
            field=models.CharField(max_length=100, verbose_name=_("操作系统")),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="rid",
            field=models.CharField(blank=True, max_length=60, verbose_name=_("客户端ID")),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="username",
            field=models.CharField(blank=True, max_length=100, verbose_name=_("系统用户名")),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="version",
            field=models.CharField(max_length=100, verbose_name=_("客户端版本")),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="alias",
            field=models.CharField(max_length=30, verbose_name=_("别名")),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="hostname",
            field=models.CharField(max_length=30, verbose_name=_("操作系统名")),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="platform",
            field=models.CharField(max_length=30, verbose_name=_("平台")),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="rhash",
            field=models.CharField(max_length=60, verbose_name=_("设备链接密码")),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="rid",
            field=models.CharField(max_length=60, verbose_name=_("客户端ID")),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="tags",
            field=models.CharField(max_length=30, verbose_name=_("标签")),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="uid",
            field=models.CharField(max_length=16, verbose_name=_("用户ID")),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="username",
            field=models.CharField(max_length=20, verbose_name=_("系统用户名")),
        ),
        migrations.AlterField(
            model_name="rustdesktag",
            name="tag_color",
            field=models.CharField(blank=True, max_length=60, verbose_name=_("标签颜色")),
        ),
        migrations.AlterField(
            model_name="rustdesktag",
            name="tag_name",
            field=models.CharField(max_length=60, verbose_name=_("标签名称")),
        ),
        migrations.AlterField(
            model_name="rustdesktag",
            name="uid",
            field=models.CharField(max_length=16, verbose_name=_("所属用户ID")),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="access_token",
            field=models.CharField(
                blank=True, max_length=60, verbose_name=_("access_token")
            ),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("登录时间")),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="uid",
            field=models.CharField(max_length=16, verbose_name=_("用户ID")),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="username",
            field=models.CharField(max_length=20, verbose_name=_("用户名")),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="uuid",
            field=models.CharField(max_length=60, verbose_name=_("uuid")),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name=_("生成时间")),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="is_expired",
            field=models.BooleanField(default=False, verbose_name=_("是否过期")),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name=_("是否使用")),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="peers",
            field=models.CharField(max_length=20, verbose_name=_("机器ID列表")),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="shash",
            field=models.CharField(max_length=60, verbose_name=_("链接Key")),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="uid",
            field=models.CharField(max_length=16, verbose_name=_("用户ID")),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="deviceInfo",
            field=models.TextField(blank=True, verbose_name=_("登录信息:")),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name=_("是否激活")),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name=_("是否管理员")),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=50, unique=True, verbose_name=_("用户名")),
        ),
    ]