# Generated by Django 5.0.3 on 2024-04-17 08:35

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rustdesdevice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=_('ID'))),
                ('action', models.CharField(max_length=20, null=True, verbose_name=_('Action'))),
                ('conn_id', models.CharField(max_length=10, null=True, verbose_name=_('Connection ID'))),
                ('from_ip', models.CharField(max_length=30, null=True, verbose_name=_('From IP'))),
                ('from_id', models.CharField(max_length=20, null=True, verbose_name=_('From ID'))),
                ('rid', models.CharField(max_length=20, null=True, verbose_name=_('To ID'))),
                ('conn_start', models.DateTimeField(null=True, verbose_name=_('Connected'))),
                ('conn_end', models.DateTimeField(null=True, verbose_name=_('Disconnected'))),
                ('session_id', models.CharField(max_length=60, null=True, verbose_name=_('Session ID'))),
                ('uuid', models.CharField(max_length=60, null=True, verbose_name=_('uuid'))),
            ],
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=_('ID'))),
                ('file', models.CharField(max_length=500, verbose_name=_('Path'))),
                ('remote_id', models.CharField(default='0', max_length=20, verbose_name=_('Remote ID'))),
                ('user_id', models.CharField(default='0', max_length=20, verbose_name=_('User ID'))),
                ('user_ip', models.CharField(default='0', max_length=20, verbose_name=_('User IP'))),
                ('filesize', models.CharField(default='', max_length=500, verbose_name=_('Filesize'))),
                ('direction', models.IntegerField(default=0, verbose_name=_('Direction'))),
                ('logged_at', models.DateTimeField(null=True, verbose_name=_('Logged At'))),
            ],
        ),
    ]